config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  post 'buyers/confirm' => "buyers#confirm"
  post 'purchases/pay' => "purchases#pay"
  get 'purchases/done' => "purchases#done"
  root 'products#index'

  resources :customers,only: [:show,:edit,:update] do
  	resources :buyers, only: [:new,:create,:edit,:update,:destroy]
  	resources :cards, only: [:new,:create,:edit,:update,:destroy]
  end
  resources :products,only: [:show,:edit,:update,:new,:create,:destroy] do
  	resource :comments, only: [:create]
  	resources :comments, only: [:new]
  	resource :favorites, only: [:create,:destroy]
  	resources :images, only: [:new,:create,:edit,:update,:destroy]
  	resources :brands, only: [:new,:create,:edit,:update]
  	resources :purchases, only: [:index]
  	resources :categorys, only: [:index]

  end
  resources :comments, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :products
end

app/models/buyer.rb
class Buyer < ApplicationRecord
	belongs_to :customer
end

app/models/card.rb
class Card < ApplicationRecord
	belongs_to :customer
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, dependent: :destroy
  has_many :buyers, dependent: :destroy
  has_many :cards, dependent: :destroy
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :images
  	belongs_to :customer, dependent: :destroy
  	belongs_to :category, dependent: :destroy
  	belongs_to :brand, dependent: :destroy
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

	def new
	end

	def create
	end

	def edit
	end

	def update
	end

end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController

	def new
	end

	def create
	end

	def edit
	end

	def update
	end

	def destroy
	end


end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	
	def new
	end

	def create
	end

	def edit
	end

	def update
	end
	
	def destroy
	end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	def new
	end

	def create
	end

	def edit
	end

	def update
	end

	def destroy
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@q = Product.ransack(params[:q])
  		@products = @q.result(distinct: true)
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		@product.customer_id = current_customer.id
		if
			@product.save
			redirect_to products_path
		else
			render "new"
		end
	end

	def show
	end

	def edit
	end

	def update
	end

	def destroy
	end

	private

	def product_params
		params.require(:product).permit(:name, :price, :description, :status, :size, :shipping_cost, :shipping_days, :prefecture_id, :judgment, :shipping_id)
	end

end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController

	def index
	end

	def pay
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/views/products/index.html.erb
<header>
      <div id="head">
        <div class="logo">
          <h1>Akina<span class="logo-title">_</span>i</h1>
        </div>
          <div class="search">
            <%= search_form_for @q do |f| %>
              <%= f.label :name, "商品" %>
              <%= f.search_field :name_cont %>
            <%= f.submit "検索" %>
            <% end %>
          </div>
          <nav>
            <% if customer_signed_in? %>
            <ul class="global-nav">
              <li class="nav-item"><i class="fas fa-align-left"></i><a href="#"> カテゴリーから探す</a></li>
              <li class="nav-item1"><i class="fas fa-tags"></i><a href="#">ブランドから探す</a></li>
              <li class="nav-item3"><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete %></a></li>
            </ul>
            <% else %>
            <ul class="global-nav">
              <li class="nav-item"><i class="fas fa-align-left"></i><a href="#"> カテゴリーから探す</a></li>
              <li class="nav-item1"><i class="fas fa-tags"></i><a href="#">ブランドから探す</a></li>
              <li class="nav-item2"><%= link_to '新規会員登録', new_customer_registration_path %></li>
              <li class="nav-item3"><%= link_to 'ログイン', new_customer_session_path %></li>
            </ul>
            <% end %>
          </nav>
      </div>
    </header>

<% if customer_signed_in? %>
	<div class="iine-main-box">
		<div class="iine-box">
			<div class="iine-category">
				いいね！した商品
			</div>
			<div class="product-view">
				すべて見る >
			</div>
			<div class="iine-image">
			</div>
		</div>
	</div>
<% end %>

<div class="category-box">
	<div class="category-header">
		<div class="subtitle">
			人気のカテゴリー
		</div>
		<div class="categorys">
			<ul class="nav">
		  		<li class="nav-products">
		    		レディース
		  		</li>
		  		<li class="nav-products">
		    		メンズ
		  		</li>
		  		<li class="nav-products">家電・スマホ・カメラ
		  		</li>
		  		<li class="nav-products">
		    		おもちゃ・ホビー・グッズ
		  		</li>
			</ul>
		</div>
	</div>
	<div class="sub-box">
		<div class="category-name">
			レディース新着アイテム
		</div>
		<div class="product-view">
			すべて見る >
		</div>
		<div class="category-product">
			<div class="product-image">
			</div>
			<div class="product-name">
				Tシャツ
			</div>
		</div>
	</div>
</div>

<div class="brand-box">
	<div class="brand-header">
		<div class="subtitle">
			人気のブランド
		</div>
		<div class="brands">
			<ul class="nav">
	  			<li class="nav-products">
	    			シャネル
	  			</li>
	  			<li class="nav-products">
	  				ルイヴィトン
	  			</li>
	  			<li class="nav-products">
	    			シュプリーム
	  			</li>
	  			<li class="nav-products">
	    			ナイキ
	  			</li>
			</ul>
		</div>
	</div>
	<div class="sub-box">
		<div class="brand-name">
			シャネル新着アイテム
		</div>
		<div class="product-view">
			すべて見る >
		</div>
		<div class="brand product">
			<div class="product-image">
			</div>
			<div class="product-name">
				財布
			</div>
		</div>
	</div>
</div>
<div class="new-button">
	<%= link_to (new_product_path) do %>
    <img class="new-button-image" src="/assets/カメラマーク.jpg" alt="">
    <% end %>
</div>

app/views/products/new.html.erb
<div class="exhibit-box">
	<div class="exhibit-sub-box">
		<%= form_for(@product) do |f| %>
			<div class="exhibit-image-box">
				<div class="exhibit-title">
					出品画像
				</div>
				<p class="exhibit-text">
					最大10枚までアップロードできます
				</p>
			</div>
			<div class="exhibit-product-box">
				<div class="exhibit-title">
					商品名
				</div>
				<%= f.text_field :name, style:"width: 100%", placeholder:"40文字まで" %>
				<div class="exhibit-title">
					商品の説明
				</div>
				<%= f.text_area :description, style:"width: 100%", placeholder:"商品の説明（必須 1,000文字以内
					（色、素材、重さ、定価、注意点など）

					例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" %>
			</div>
			<div class="exhibit-product-detail-box">
				<div class="exhibit-explanation">
					商品の詳細
				</div>
				<div class="exhibit-title">
					カテゴリー
				</div>
				<div class="exhibit-title">
					ブランド
				</div>
				<div class="exhibit-title">
					商品の状態
				</div>
			</div>
			<div class="exhibit-shipping-box">
				<div class="exhibit-explanation">
					配送について
				</div>
				<div class="exhibit-title">
					配送料の負担
				</div>
				<div class="exhibit-title">
					配送元の地域
				</div>
				<div class="exhibit-title">
					発送までの日数
				</div>
			</div>
			<div class="exhibit-price-box">
				<div class="exhibit-explanation">
					価格（¥300〜9,999,999)
				</div>
				<div class="exhibit-title">
					販売価格
				</div>
				<%= f.text_field :price, style:"width: 100%" %>
				<div class="exhibit-text">
					販売手数料（10%）
				</div>
			</div>
			<div class="exhibit-profit-box">
				<div class="exhibit-text">
					販売利益
				</div>
			</div>
			<%= f.submit "出品する", class:"btn btn-primary active" %>
		<% end %>
	</div>
</div>